version: "3.8"

services:
  gmp:
    build:
      context: ./gmp
    volumes:
      - ./gmp:/home/software/gmp:rw
    image: gmp:R15.0.6
    command: mvn pax:provision
    ports:
      - 61616:61616
    expose: [61616]
  giapi-glue-ext:
    build:
      context: ./giapi-glue-cc/external/
    image: giapi-glue-external:R15
    volumes:
      - ./giapi-glue-cc/external:/home/software/giapi-glue-cc/external

  giapi-glue-lib:
    build:
      context: ./giapi-glue-cc
    image: giapi-glue-build:R15
    volumes:
      - ./giapi-glue-cc/src:/home/software/giapi-glue-cc/src
    depends_on: [gmp] 
    links:
      - gmp
